version: '3'

services:
    cloud:
        build: .docker
        container_name: cloud
        ports:
            - "8080:80"
    db:
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: "root@123"
        volumes: 
            - "./mysql.cnf:/etc/mysql/conf.d/mysql.cnf"
            - "./tmp/db:/var/lib/mysql"
volumes: 
    data: